import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");

const defaultDataSourceConfigPath = resolve(rootDir, "data-source.json");
const defaultOutputPath = resolve(rootDir, "src", "data.generated.ts");
const packageJsonPath = resolve(rootDir, "package.json");
const schoolYear = "2020-2021";
const sourceOrganization = "gov.ph";

const expectedKeys = [
  "Region",
  "Division",
  "District",
  "BEIS School ID",
  "School Name",
  "Street Address",
  "Municipality",
  "Legislative District",
  "Barangay",
  "Sector",
  "Urban/Rural",
  "School Subclassification",
  "Modified Curricural Offering Classification"
];

const outputRawRecordType = "SchoolRecordRaw";

function resolveInputPath(inputPath) {
  return isAbsolute(inputPath) ? inputPath : resolve(rootDir, inputPath);
}

function assertRecordShape(records) {
  if (!Array.isArray(records)) {
    throw new Error("Expected source JSON to be an array of records.");
  }

  if (records.length === 0) {
    throw new Error("Source JSON is empty.");
  }

  const first = records[0];
  const firstKeys = Object.keys(first);

  for (const key of expectedKeys) {
    if (!firstKeys.includes(key)) {
      throw new Error(`Missing expected key in first record: ${key}`);
    }
  }

  for (const [index, record] of records.entries()) {
    if (typeof record !== "object" || record === null || Array.isArray(record)) {
      throw new Error(`Record at index ${index} is not a valid object.`);
    }

    for (const key of expectedKeys) {
      if (!(key in record)) {
        throw new Error(`Record at index ${index} is missing key: ${key}`);
      }
      if (typeof record[key] !== "string") {
        throw new Error(`Record at index ${index} has non-string value for key: ${key}`);
      }
    }
  }
}

function escapeTemplateLiteralValue(value) {
  if (value.includes("\t") || value.includes("\n") || value.includes("\r")) {
    throw new Error("Record contains tab/newline/carriage-return which is unsupported in compact payload.");
  }

  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${");
}

function parseDataSourceConfig(configRaw) {
  const config = JSON.parse(configRaw);

  if (typeof config !== "object" || config === null || Array.isArray(config)) {
    throw new Error("data-source.json must be an object.");
  }

  for (const key of ["repo", "tag", "path", "sha256"]) {
    if (typeof config[key] !== "string" || config[key].trim().length === 0) {
      throw new Error(`data-source.json is missing required string field: ${key}`);
    }
  }

  return {
    repo: config.repo.trim(),
    tag: config.tag.trim(),
    path: config.path.trim(),
    sha256: config.sha256.trim().toLowerCase()
  };
}

function toRawGithubUrl(repo, tag, path) {
  const normalizedRepo = repo
    .replace(/^https:\/\/github\.com\//, "")
    .replace(/\.git$/, "")
    .replace(/^\/+|\/+$/g, "");
  return `https://raw.githubusercontent.com/${normalizedRepo}/${tag}/${path}`;
}

function sha256Hex(content) {
  return createHash("sha256").update(content).digest("hex");
}

async function fetchRemoteData(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download dataset from ${url} (HTTP ${response.status})`);
  }
  return response.text();
}

function buildGeneratedModule({
  packageVersion,
  sourceFileName,
  tsvPayload
}) {
  const rawObjectLines = expectedKeys
    .map((key, index) => `      ${JSON.stringify(key)}: cols[${index}]`)
    .join(",\n");

  return `// This file is auto-generated by scripts/generate-data.mjs.
// Do not edit manually.

import type { ${outputRawRecordType} } from "./types";

export const schoolYear = ${JSON.stringify(schoolYear)} as const;
export const sourceFile = ${JSON.stringify(sourceFileName)} as const;
export const packageVersion = ${JSON.stringify(packageVersion)} as const;

const compactPayload = \`${tsvPayload}\`;

function parseRawRecords(payload: string): ${outputRawRecordType}[] {
  if (payload.length === 0) {
    return [];
  }

  return payload.split("\\n").map((line, rowIndex) => {
    const cols = line.split("\\t");
    if (cols.length !== ${expectedKeys.length}) {
      throw new Error(
        \`Invalid compact payload column count at row \${rowIndex}: expected ${expectedKeys.length}, got \${cols.length}\`
      );
    }
    return {
${rawObjectLines}
    };
  });
}

export const rawRecords = parseRawRecords(compactPayload);
`;
}

async function loadSourcePayload(dataSourceConfig, configPath) {
  const localOverride = process.env.PH_SCHOOLS_DATA_PATH;
  if (localOverride) {
    const overridePath = resolveInputPath(localOverride);
    const payload = await readFile(overridePath, "utf8");
    console.log(`Using local dataset override: ${overridePath}`);
    return {
      payload,
      sourceFileName: basename(overridePath),
      checksumValidated: false
    };
  }

  const sourceUrl = toRawGithubUrl(dataSourceConfig.repo, dataSourceConfig.tag, dataSourceConfig.path);
  const payload = await fetchRemoteData(sourceUrl);
  const actualChecksum = sha256Hex(payload);

  if (actualChecksum !== dataSourceConfig.sha256) {
    throw new Error(
      `Checksum mismatch for ${sourceUrl}: expected ${dataSourceConfig.sha256}, got ${actualChecksum}. ` +
      `Update ${configPath} only after verifying the dataset release.`
    );
  }

  return {
    payload,
    sourceFileName: basename(dataSourceConfig.path),
    checksumValidated: true
  };
}

async function main() {
  const configPath = process.env.PH_SCHOOLS_DATA_SOURCE_CONFIG
    ? resolveInputPath(process.env.PH_SCHOOLS_DATA_SOURCE_CONFIG)
    : defaultDataSourceConfigPath;
  const outputPath = process.env.PH_SCHOOLS_DATA_OUTPUT_PATH
    ? resolveInputPath(process.env.PH_SCHOOLS_DATA_OUTPUT_PATH)
    : defaultOutputPath;

  const [rawPackageJson, rawConfig] = await Promise.all([
    readFile(packageJsonPath, "utf8"),
    readFile(configPath, "utf8")
  ]);

  const packageJson = JSON.parse(rawPackageJson);
  const packageVersion = String(packageJson.version ?? "0.0.0");
  const dataSourceConfig = parseDataSourceConfig(rawConfig);

  const source = await loadSourcePayload(dataSourceConfig, configPath);
  const records = JSON.parse(source.payload);
  assertRecordShape(records);

  const tsvPayload = records
    .map((record) =>
      expectedKeys
        .map((key) => escapeTemplateLiteralValue(record[key]))
        .join("\t")
    )
    .join("\n");

  const content = buildGeneratedModule({
    packageVersion,
    sourceFileName: source.sourceFileName,
    tsvPayload
  });

  await writeFile(outputPath, content, "utf8");

  console.log(`Generated ${outputPath}`);
  console.log(`Records embedded: ${records.length}`);
  if (source.checksumValidated) {
    console.log(`Checksum validated against data-source.json (${sourceOrganization})`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
