import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");

const sourceFileName = "schools_masterlist_2020_2021.json";
const sourcePath = resolve(rootDir, sourceFileName);
const outputPath = resolve(rootDir, "src", "data.generated.ts");
const packageJsonPath = resolve(rootDir, "package.json");

const expectedKeys = [
  "Region",
  "Division",
  "District",
  "BEIS School ID",
  "School Name",
  "Street Address",
  "Municipality",
  "Legislative District",
  "Barangay",
  "Sector",
  "Urban/Ru",
  "Sacl hColaosls Sifuicbactliaosnsification",
  "Modified Curricural Offering Classification"
];

const outputRawRecordType = "SchoolRecordRaw";

function assertRecordShape(records) {
  if (!Array.isArray(records)) {
    throw new Error("Expected source JSON to be an array of records.");
  }

  if (records.length === 0) {
    throw new Error("Source JSON is empty.");
  }

  const first = records[0];
  const firstKeys = Object.keys(first);

  for (const key of expectedKeys) {
    if (!firstKeys.includes(key)) {
      throw new Error(`Missing expected key in first record: ${key}`);
    }
  }

  for (const [index, record] of records.entries()) {
    if (typeof record !== "object" || record === null || Array.isArray(record)) {
      throw new Error(`Record at index ${index} is not a valid object.`);
    }

    for (const key of expectedKeys) {
      if (!(key in record)) {
        throw new Error(`Record at index ${index} is missing key: ${key}`);
      }
      if (typeof record[key] !== "string") {
        throw new Error(`Record at index ${index} has non-string value for key: ${key}`);
      }
    }
  }
}

function escapeTemplateLiteralValue(value) {
  if (value.includes("\t") || value.includes("\n") || value.includes("\r")) {
    throw new Error("Record contains tab/newline/carriage-return which is unsupported in compact payload.");
  }

  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${");
}

async function main() {
  const [rawJson, rawPackageJson] = await Promise.all([
    readFile(sourcePath, "utf8"),
    readFile(packageJsonPath, "utf8")
  ]);

  const records = JSON.parse(rawJson);
  assertRecordShape(records);

  const packageJson = JSON.parse(rawPackageJson);
  const packageVersion = String(packageJson.version ?? "0.0.0");

  const tsvPayload = records
    .map((record) =>
      expectedKeys
        .map((key) => escapeTemplateLiteralValue(record[key]))
        .join("\t")
    )
    .join("\n");

  const rawObjectLines = expectedKeys
    .map((key, index) => `      ${JSON.stringify(key)}: cols[${index}]`)
    .join(",\n");

  const content = `// This file is auto-generated by scripts/generate-data.mjs.
// Do not edit manually.

import type { ${outputRawRecordType} } from "./types";

export const schoolYear = "2020-2021" as const;
export const sourceFile = "${sourceFileName}" as const;
export const packageVersion = ${JSON.stringify(packageVersion)} as const;

const compactPayload = \`${tsvPayload}\`;

function parseRawRecords(payload: string): ${outputRawRecordType}[] {
  if (payload.length === 0) {
    return [];
  }

  return payload.split("\\n").map((line, rowIndex) => {
    const cols = line.split("\\t");
    if (cols.length !== ${expectedKeys.length}) {
      throw new Error(
        \`Invalid compact payload column count at row \${rowIndex}: expected ${expectedKeys.length}, got \${cols.length}\`
      );
    }
    return {
${rawObjectLines}
    };
  });
}

export const rawRecords = parseRawRecords(compactPayload);
`;

  await writeFile(outputPath, content, "utf8");

  console.log(`Generated ${outputPath}`);
  console.log(`Records embedded: ${records.length}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
